# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ReactNativeStarterKit' do
  pod 'Firebase/Core', '~> 5.3.0'

end

target 'ReactNativeStarterKit-tvOS' do
end
