# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ReactNativeStarterKit' do
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end

target 'ReactNativeStarterKit-tvOS' do
end
